MEMORY
{
    RAM_LOW : ORIGIN = 0x08000000, LENGTH = 64K
    RAM_HIGH : ORIGIN = 0x20000000, LENGTH = 192K
    FLASH : ORIGIN = 0x00000000, LENGTH = 1M
}

REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", RAM_LOW);
REGION_ALIAS("REGION_BSS", RAM_LOW);
REGION_ALIAS("REGION_STACK", RAM_LOW);
REGION_ALIAS("REGION_HEAP", RAM_HIGH);
